//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreQualTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Income { get; set; }
        public Nullable<int> CardID { get; set; }
        public int ID { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
